# Inserts a blank line between shell prompts
# add_newline = false

# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

[character]
# Replace the ❯ symbol in the prompt with ➜ in success and x in error
success_symbol = "[➜](bold green)"
error_symbol = "[X](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[aws]
format = 'on [$symbol ($profile )(\($region\) )]($style)'
# style = "bold blue"
symbol = "☁"



